# Generated by Django 5.1.7 on 2025-07-17 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rooms',
            old_name='user',
            new_name='owner',
        ),
    ]
