# Generated by Django 5.1.7 on 2025-07-17 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_user_rooms_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='is_booked',
            field=models.BooleanField(default=False),
        ),
    ]
