# Generated by Django 5.1.7 on 2025-07-17 18:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rooms_is_booked'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='booked_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='booked_rooms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_rooms', to=settings.AUTH_USER_MODEL),
        ),
    ]
