# Generated by Django 5.1.7 on 2025-07-23 18:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rooms_booked_by_alter_rooms_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='booked_by',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='booked_rooms', to=settings.AUTH_USER_MODEL),
        ),
    ]
