# Generated by Django 5.1.7 on 2025-07-23 18:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_rooms_booked_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='booked_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booked_rooms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='is_booked',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
